---
- name: Ruby dependencies
  apt: name={{item}} state=installed
  sudo: yes
  with_items:
    - curl
    - git-core
    - libcurl4-openssl-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - sqlite3
    - zlib1g-dev
