---
- name: Ruby dependencies
  apt: name={{item}} state=installed
  sudo: yes
  with_items:
    - build-essential
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libyaml-dev 
    - zlib1g-dev

- name: Determine whether ruby-install is installed
  stat: path=/usr/local/bin/ruby-install
  register: ruby_install

- name: Download ruby-install
  get_url: url=https://github.com/postmodern/ruby-install/archive/v0.4.3.tar.gz
           dest=/tmp/ruby-install-v0.4.3.tar.gz
  when: not ruby_install.stat.exists

- name: Extract ruby-install
  command: >
    chdir=/tmp
    tar -zxf ruby-install-v0.4.3.tar.gz
    creates=/tmp/ruby-install-0.4.3
  when: not ruby_install.stat.exists

- name: Install ruby-install
  command: >
    chdir=/tmp/ruby-install-0.4.3 
    creates=/usr/local/bin/ruby-install
    sudo make install
  when: not ruby_install.stat.exists

- name: Install ruby {{ruby_version}}
  command: >
    chdir=/tmp
    ruby-install ruby {{ruby_version}} --no-reinstall --src-dir /tmp

- name: Download chruby
  get_url: >
    url=https://github.com/postmodern/chruby/archive/v0.3.8.tar.gz
    dest=/tmp/chruby-0.3.8.tar.gz

- name: Extract chruby
  command: >
    chdir=/tmp
    tar -zxf chruby-0.3.8.tar.gz
    creates=/tmp/chruby-0.3.8

- name: Install chruby
  command: >
    chdir=/tmp/chruby-0.3.8
    creates=/usr/local/share/chruby
    sudo make install

- name: Set default ruby to {{ ruby_version }}
  lineinfile: >
    dest=~/.ruby-version
    state=present
    line="ruby-{{ruby_version}}" create=yes

- name: Enable chroot
  lineinfile: >
    dest=~/.profile
    state=present
    line="source /usr/local/share/chruby/chruby.sh"

- name: Use ruby {{ ruby_version }}
  lineinfile: >
    dest=~/.profile
    state=present
    line="source /usr/local/share/chruby/auto.sh"
