---
- name: Dependencies
  apt: name={{ item }} state=installed
  become: yes
  with_items:
    - build-essential
    - git
    - libssl-dev
    - curl

- name: Clone nvm
  git: >
    repo=https://github.com/creationix/nvm.git
    dest=~/.nvm
    update=yes

- name: Enable nvm
  lineinfile: >
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
    state=present

- name: Install nodejs
  command: sudo -iu $USER nvm install {{nodejs_version}}

- name: Set default nodejs
  command: sudo -iu $USER nvm alias default {{nodejs_version}}
