---
- name: Install default packages
  apt: name={{item}} state=installed
  sudo: yes
  with_items:
    - xfce4
    - gdm
    - virtualbox-guest-dkms
    - virtualbox-guest-utils
    - virtualbox-guest-x11

- name: Configure X11
  sudo: yes
  lineinfile: >
    dest=/etc/X11/Xwrapper.config
    regexp=^allowed_users=
    line=allowed_users=anybody

- name: Configure dgm
  sudo: yes
  command: dpkg-reconfigure gdm
