#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "chromedriver", github: "DrTom/ansible-role-chromedriver"
role "postgres",     github: "geerlingguy/ansible-role-postgresql"
role "rvm",          github: "rvm/rvm1-ansible"
role "swapfile",     github: "kamaln7/ansible-swapfile"
