---
- hosts: all

  pre_tasks:
    - name: Update packages
      apt: upgrade=yes update_cache=yes cache_valid_time=3600
      become: yes
      tags: ['packages']

    - name: Required packages
      apt: name={{item}} state=installed
      become: yes
      with_items:
        - curl
        - git
      tags: ['packages']

    - command: locale-gen en_US en_US.UTF-8
      become: yes
      tags: ['locale']

    - lineinfile: >
        dest=/etc/default/locale
        state=present
        line='LC_ALL="en_US.UTF-8"'
      become: yes
      tags: ['locale']

    - name: Setup time zone
      become: yes
      file: >
        dest=/etc/localtime
        src=/usr/share/zoneinfo/Asia/Ho_Chi_Minh
        state=link
        force=yes
      tags: ['workstation']

    - name: Setup host name (workstation)
      become: yes
      shell: >
        echo workstation > /etc/hostname
      tags: ['workstation']

  roles:
    - {
      role: postgresql,
      tags: ['postgresql'],
      become: yes
    }
    - {
      role: rvm,
      tags: ['ruby'],
      rvm1_user: vagrant,
      rvm1_rubies: rvm1_rubies,
      rvm1_default_ruby_version: rvm1_default_ruby_version
    }
    - {
      role: nodejs,
      tags: ['nodejs'],
      nodejs_version: nodejs_version,
    }
    - {
      role: workstation,
      tags: ['workstation']
    }

  tasks:
    - shell: bash -lc 'gem list'
      register: gem_list
      tags: ['gems']

    - name: Update gem
      command: bash -lc 'gem update --system'
      tags: ['gems']

    - name: Install default ruby gems
      command: bash -lc 'gem install {{item}}'
      when: item not in gem_list.stdout
      with_items:
        - bundler
        - pry
        - tmuxinator
      tags: ['gems']
